name: Node.js sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        node-version: 18
        cache: 'npm'
        check-latest: true
        architecture: 'x64'
      
    - run: npm ci
    - run: npm install --save-exact esbuild 
    - run: ./node_modules/.bin/esbuild
    - run: ./node_modules/.bin/esbuild app.js --bundle --platform=node --outfile=build/out.js
    - run: |
          git add -A
          git commit -m "Git node build out file commit"
          git push
 
